collectd/go-collectd

network/buffer.go, network/buffer_test.go, network/parse.go, network/parse_test.go
I did some work [1] with https://github.com/dvyukov/go-fuzz and found and fixed couple of crashers; at least one of which as a DoS vector. 
[1] https://github.com/ryancox/go-collectd/blob/fuzztests/network/fuzz.go ... I'll submit a PR for this when the cdtime PR is merged in
=> fixes based on go-fuzz runs

.travis.yml
Setup a travis CI job with this file to find broken builds, go vet and golint errors. 
Once you are happy with this, you can uncomment the last two lines to notify via IRC if build is broken
See: https://travis-ci.org/ryancox/go-collectd
=> Adding Travis CI file

cdtime/cdtime_test.go, format/graphite.go
Two fixes I noticed failing go vet on travis:
- cdtime_test.go: missing an argument in call to Errorf
- graphite.go: it looked legit to me. i think go vet was confused. changing to a `%v` is functional and satisfies go vet
=> go vet fixes

LICENSE, api/types.go, api/types_test.go, network/buffer.go, network/parse.go, network/parse_test.go, network/server.go
This patch adds support for reading collectd's *types.db(5)* files and creating *ValueList* types based on these definitions. It also adds support to the *network* package so that the *[]ValueList* returned by *Parse()* have the *DSNames* field set.
Values may also be cast to the correct "data source type". This is similar to the way *collectd* behaves, though collectd will simply access the wrong type of a union, without a cast, causing quite erratic behavior.
Fixes: #13
=> Package api: Implement the TypesDB class.

api/json.go, api/json_test.go, api/main.go, exec/exec.go, exec/exec_test.go, export/export.go, export/export_test.go, format/graphite.go, format/graphite_test.go, format/putval.go, network/buffer.go, network/buffer_test.go, network/client.go, network/client_test.go, network/parse.go, network/parse_test.go, network/server.go, network/server_test.go, plugin/plugin.go
This changes the API in two ways:
*   All functions return or accept a *pointer* to a `ValueList` now. Previously `ValueList`s were passed by value, which is a bit too expensive given the struct's size.
*   The `api.Writer` interface now passes a `context.Context` to the write function. The `context` package is new in Go 1.7, so that version is required with this change.
=> All packages: API changes

README.md
`Write()` is now expecting a context as first argument. Provides an empty one in the example provided in `README.md`
=> doc: update README.md to use context

plugin/plugin.go
Hi @octo,
This PR fixes the following compilation issue:
```
../go/src/collectd.org/plugin/plugin.go:290: invalid operation: i < ds.ds_num (mismatched types C.size_t and C.int)
```
Let me know if this change suits you.
Regards,
Vincent
=> Fix types mismatch in 'plugin' package

README.md
- would give "cannot use vl (type api.ValueList) as type *api.ValueList in argument to exec.Putval.Write" before
=> minor correction to README example

plugin/c.go, plugin/plugin.go
Hi,
This patch introduces support for the Shutdown callback in Go plugins, modeled after the existing read and write callbacks. If it's of use I'd be happy to have a crack at implementing the remaining callbacks. Any and all feedback would be appreciated.
Kind regards,
Ashley
=> Package plugin: Add support for Shutdown callback

network/server.go, network/server_test.go
This allows to cleanly shut down the receiving goroutine.
=> Package network: Check for a cancelled context in Server.ListenAndWrite().

network/main.go
This is an integer variant of DefaultService for use in places that expect
integers.
=> Package network: Add the DefaultPort constant.

plugin/c.go
`value_list_add()` called `realloc(3)` with the number of _elements_ required, not the number of bytes. This caused a buffer overflow which only lead to a segfault with a sufficiently large number of data sources.
Fixes: #26
=> Package plugin: Fix memory allocation bug in value_list_add().

plugin/plugin.go
The previous example incorrectly passed a context to Write,
unnecessarily exported the "examplePlugin" type and unnecessarily used a
reference.
=> Package plugin: Improve example plugin code.

plugin/plugin.go
This adds context, i.e. which function returned an error via errno.
=> Package plugin: Wrap C errors.

plugin/plugin.go
With this change, a `context.Context` is passed to the read and shutdown callbacks. The `plugin.Write()` function now also expects a context, mostly for consistency but it checks that the context is not expired before passing metrics on to the daemon.
A follow-up change adds the name of the callback to the context, so it is available to the plugin code.
=> Package plugin: Pass a context.Context to callbacks and Write().

plugin/fake/log.go, plugin/fake/read.go, plugin/fake/write.go, plugin/plugin.go
These strings are actively used for the lifetime of the daemon, so it's not really a "leak", but not freeing these strings at shutdown is simply not good style.
=> Package plugin: Free strings allocated in the register functions.

exec/exec.go, exec/exec_test.go, exec/exec_x_test.go
This adds two tests, one for "void" and one for "value" callbacks. The tests are implemented in an external package and don't have access to "exec"'s private types and fields.
This change also adds the code required to return from `Executor.Run()` when the context is canceled.
=> Package exec: Add functional test, fix context cancellation.

network/server_test.go
Tests were getting "port in use" errors occasionally.
=> Package network: Listen to random port when spinning up test server.

plugin/c.go, plugin/fake/fake.go, plugin/fake/read.go, plugin/plugin.go
I considered, and had already implemented, a `WithoutTimeout` option that could be passed to `RegisterRead`. My idea was to provide plugins with a long-lived context, in case they need to establish connections or the like. However, it turns out that all examples I looked at, e.g. `"net".Dialer.DialContext` and `"google.golang.org/grpc".DialContext` return connections which are not affected by the context's cancellation. So I decided to keep the API simple and add a `WithoutTimeout` option if and when somebody comes up with a use case.
=> Package plugin: Set a timeout on the context passed to read callbacks.

api/main.go, api/main_test.go
From a user's perspective the difference is small:
*   `Fanout` blocks until all writers have finished. `Dispatcher` used to return immediately. This makes the wrapped writers' errors accessible. This required dealing with context cancellation gracefully.
*   `Fanout` is based on `[]Writer`. `Dispatcher` used to be a struct with private fields. This simplifies usage and implementation of the type.
*   `Fanout` is fully tested.
Supporting changes:
*   Turn "main_test.go" into a functional test.
*   `ValueList.Clone()` returns a copy of itself.
=> Package api: Replace the "Dispatcher" type with the "Fanout" type.

export/export.go, export/export_test.go
The `Run()` function previously didn't return, even if the context got cancelled. This was not the correct behavior.
Previously, the `Run()` function did return if any `Write()` failed, which was not documented and not the intended behavior. This has been changed to a log statement instead.
Testing of the `export` package has been improved. It now also tests the `Run()` function.
=> Package export: Add support for context cancellation and add tests.

plugin/plugin.go, plugin/plugin_test.go
=> Package plugin: Remove the Writer type.

cdtime/cdtime.go, cdtime/cdtime_test.go, plugin/plugin.go, plugin/plugin_test.go
This PR also improves the documentation around which fields are automatically populated if empty. A corner case in `cdtime.New()` has been fixed and a bug in the `plugin_test` has been fixed.
=> Package plugin: Automatically determine ValueList.Identifier.Plugin if empty.

api/json.go, api/json_test.go, api/main.go, format/putval.go, format/putval_test.go, meta/meta.go, meta/meta_test.go, plugin/c.go, plugin/fake/meta_data.c, plugin/generator/generator.go, plugin/plugin.go, plugin/plugin_test.go, plugin/wrapper.go
Meta data entries are essentially a union of a couple different types. There are multiple ways to achieve something union-like in Go and this PR is taking a relatively type save approach.
There is a usage example in `meta_test.go` which hopefully illustrates how this package is supposed to be used. I added a Meta field to api.ValueList and plumbed that field through the JSON marshalling. 
CC: @davegalos
=> Package meta: meta data for api.ValueList

config/config.go, config/config_test.go
MarshalText creates a text representation of the config that collectd
can parse.
Fixes: #84
=> Package config: Implement MarshalText.

plugin/log.go, plugin/log_test.go, plugin/plugin_test.go
`LogWriter` implements the `io.Writer` interface on top of collectd's logging infrastructure. This allows, for example, to create a `log.Logger` writing to the collectd log.
=> Package plugin: Add the LogWriter type.

config/config.go, config/config_test.go, plugin/config.go
This reduces differences between the `config` and the `meta` package, avoiding unnecessary cognitive load.
=> Package config: Drop the "Value" suffix from "{Bool,Float64,String}Value".

api/main.go, api/main_test.go
This new function does a sanity check on a `ValueList`, e.g. checking that the Host field is set and that the number of values and DS names match.
In particular, the need to check for duplicate data source names came up in prometheus/collectd_exporter#78.
=> Package api: Implement ValueList.Check().
